-- Security & Performance Optimization Migration
-- Generated by Database Architect Agent

-- 1. Add missing indexes for Foreign Keys in AI Agent tables
-- These are critical for JOIN performance and cascading deletes

-- agent_conversations
CREATE INDEX IF NOT EXISTS idx_agent_conversations_company ON public.agent_conversations(company_id);
CREATE INDEX IF NOT EXISTS idx_agent_conversations_customer ON public.agent_conversations(customer_id);
CREATE INDEX IF NOT EXISTS idx_agent_conversations_ticket ON public.agent_conversations(ticket_id);

-- agent_execution_logs
CREATE INDEX IF NOT EXISTS idx_agent_execution_logs_company ON public.agent_execution_logs(company_id);
CREATE INDEX IF NOT EXISTS idx_agent_execution_logs_conversation ON public.agent_execution_logs(conversation_id);

-- agent_messages
CREATE INDEX IF NOT EXISTS idx_agent_messages_conversation ON public.agent_messages(conversation_id);

-- ai_agent_conversations
CREATE INDEX IF NOT EXISTS idx_ai_agent_conversations_agent ON public.ai_agent_conversations(agent_id);
CREATE INDEX IF NOT EXISTS idx_ai_agent_conversations_company ON public.ai_agent_conversations(company_id);
CREATE INDEX IF NOT EXISTS idx_ai_agent_conversations_contact ON public.ai_agent_conversations(contact_id);
CREATE INDEX IF NOT EXISTS idx_ai_agent_conversations_ticket ON public.ai_agent_conversations(ticket_id);

-- ai_agent_flows
CREATE INDEX IF NOT EXISTS idx_ai_agent_flows_agent ON public.ai_agent_flows(agent_id);
CREATE INDEX IF NOT EXISTS idx_ai_agent_flows_next_stage ON public.ai_agent_flows(next_stage_id);

-- ai_agent_messages
CREATE INDEX IF NOT EXISTS idx_ai_agent_messages_conversation ON public.ai_agent_messages(conversation_id);

-- ai_agent_subagents
CREATE INDEX IF NOT EXISTS idx_ai_agent_subagents_agent ON public.ai_agent_subagents(agent_id);
CREATE INDEX IF NOT EXISTS idx_ai_agent_subagents_sub_agent ON public.ai_agent_subagents(sub_agent_id);

-- 2. Add Data Integrity Constraints

-- Ensure fees and ages are positive (Check Constraints)
ALTER TABLE public.ai_agent_knowledge_config 
  ADD CONSTRAINT check_enrollment_fee_positive CHECK (enrollment_fee_value >= 0),
  ADD CONSTRAINT check_children_min_age_positive CHECK (children_min_age >= 0);

-- 3. Optimization
-- Enable PG Stat Statements if not enabled (for query monitoring by tools)
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";
