-- Security Fix: Restrict Public Write Access to AI Agent Conversations
-- Generated by Penetration Tester Agent
-- Vulnerability: Publicly accessible INSERT/UPDATE policies allowing IDOR and Data Tampering

-- 1. Drop Insecure Policies (which allowed WITH CHECK (true))
DROP POLICY IF EXISTS "Service can insert conversations" ON public.ai_agent_conversations;
DROP POLICY IF EXISTS "Service can update conversations" ON public.ai_agent_conversations;
DROP POLICY IF EXISTS "Service can insert messages" ON public.ai_agent_messages;

-- 2. Create Secure Policies (Scoped to Company)
-- Users can only create/update conversations if they belong to the company
-- or are super_admin

CREATE POLICY "Users can create conversations for their company" ON public.ai_agent_conversations
  FOR INSERT WITH CHECK (
    company_id IN (SELECT company_id FROM public.profiles WHERE user_id = auth.uid()) OR
    EXISTS (SELECT 1 FROM public.profiles WHERE user_id = auth.uid() AND profile = 'super_admin')
  );

CREATE POLICY "Users can update conversations for their company" ON public.ai_agent_conversations
  FOR UPDATE USING (
    company_id IN (SELECT company_id FROM public.profiles WHERE user_id = auth.uid()) OR
    EXISTS (SELECT 1 FROM public.profiles WHERE user_id = auth.uid() AND profile = 'super_admin')
  );

CREATE POLICY "Users can create messages for their company conversations" ON public.ai_agent_messages
  FOR INSERT WITH CHECK (
    conversation_id IN (
      SELECT id FROM public.ai_agent_conversations 
      WHERE company_id IN (SELECT company_id FROM public.profiles WHERE user_id = auth.uid())
    ) OR
    EXISTS (SELECT 1 FROM public.profiles WHERE user_id = auth.uid() AND profile = 'super_admin')
  );

-- 3. Explicit Service Role Access
-- Service Role bypasses RLS by default, but adding explicit policies ensures clarity
-- and prevents implicit fallback to "deny all" if RLS behavior changes.

CREATE POLICY "Service role full access to ai_agent_conversations"
  ON public.ai_agent_conversations FOR ALL
  TO service_role
  USING (true);

CREATE POLICY "Service role full access to ai_agent_messages"
  ON public.ai_agent_messages FOR ALL
  TO service_role
  USING (true);
